21585: Refactored client and types, MAJOR
howsoai/howso-engine-ts pull request #19
Opened 2024-09-24 21:21 UTC by fulpm

- Types are now auto generated via the Howso Engine instead of using openapi
- Trainee methods are now generated via the Howso Engine
- Refactored type and client packages structure

2024-10-02 14:32 UTC, lancegliser requested changes

2024-10-02 14:32 UTC, lancegliser commented on src/types/schemas/ReactAggregate.ts
> +  /*
I'd love to see these property comments use the full `/**`. JS docs and IDE interpreters would pass them along.

2024-10-02 14:32 UTC, lancegliser commented on src/types/shims/FeatureOriginalType.ts
> +export interface BooleanType {
I'm a little worried about potential name collision or confusion on these with our core types. We probably need to prefix all of these with `OriginalType`. So `OriginalTypeBoolean`, or the reverse.

2024-10-02 14:32 UTC, lancegliser commented on src/types/shims/React.ts
I wonder if we need to make a point of running these sorts of long objects (all objects?) through alpha sorting.

2024-10-02 14:32 UTC, lancegliser commented on src/types/trainee.ts
> +export interface TraineeIdentity {
Let's preference `type` for these.

2024-10-02 17:59 UTC, lancegliser commented on src/client/worker/HowsoWorkerClient.ts
> +          const { payload: response } = await this.train(trainee.id, {
No access to the warning portion of this response. With `trace: true`, I did see it. Still, I wonder if we can't do better. Going to see about adding a `Logger` option that can auto log warnings if supplied internally.

2024-10-03 15:25 UTC, fulpm commented on src/types/shims/React.ts
Will come with the removal of the shims, going to leave as is for now

2024-10-03 18:20 UTC, lancegliser approved these changes

2024-10-03 18:21 UTC, merged